from enum import Enum


class GICSector(str, Enum):
    COMMUNICATION_SERVICES = "COMMUNICATION SERVICES"
    CONSUMER_DISCRETIONARY = "CONSUMER DISCRETIONARY"
    CONSUMER_STAPLES = "CONSUMER STAPLES"
    ENERGY = "ENERGY"
    FINANCIALS = "FINANCIALS"
    HEALTH_CARE = "HEALTH CARE"
    INDUSTRIALS = "INDUSTRIALS"
    INFORMATION_TECHNOLOGY = "INFORMATION TECHNOLOGY"
    MATERIALS = "MATERIALS"
    REAL_ESTATE = "REAL ESTATE"
    UTILITIES = "UTILITIES"
